### ISSUE TITLE
In the PC& mobile terminal, I have applied Rust FFI to the UE4.27&U3D production environment to do simple physical simulation

### ISSUE THREAD

**Issue by smallverse** [MaikKlein/unreal-rust#13]
Seeing this project, it's great, maybe I can contribute with

Here is the sample code https://github.com/smallverse/ue4_test

**Comment by MaikKlein** [comment]
Hey,

Can you give a quick explanation of what the code does, and where we would use it in unreal-rust?

**Comment by smallverse** [comment]
Well, my previous practice is based on Rust's c-abi or wasm, providing simple physics general simulation plugins for U3D&UE&three.js/babylon.js. The plugins themselves implement quaternions, Euler transformations, etc., for imitating mechanical table hand rotation, clothes & fabric flexibility effects, etc., and have been used for pc&mobile.

I am not currently using the unreal-rust plugin itself in a real project. But I think it is better to make a layer of plugin abstraction in the middle of unreal-rust itself, so that it can be used directly in UE project development, just as convenient as using C++, and the developers themselves don't need to pay attention to the plugin itself. The problem is that the cross-engine adaptation is not flexible.
