### ISSUE TITLE
Q: Could you use Bevy ECS?

### ISSUE THREAD

**Issue by ScottKane** [MaikKlein/unreal-rust#24]
Is the ECS managed from the C++ side of the plugin or could bevy's ECS be integrated instead from rust side? The ergonomics of their ECS would be awesome in UE

**Comment by stephanbuys** [comment]
@ScottKane the `bevy` ECS is used, see https://github.com/MaikKlein/unreal-rust/blob/main/unreal-api/Cargo.toml

**Comment by ScottKane** [comment]
@stephanbuys just got round to digging into the code deeper and noticed that, will be awesome to see where this plugin goes
